language: python
python:
  - 3.8

services:
  - docker

install:
  - docker pull rahulh25/devopsfinalshorturlapi
  - docker run -d -p 127.0.0.1:5000:5000 rahulh25/devopsfinalshorturlapi

before_script:
  - pip install -r requirements.txt
  - pip install mock
  - pip install requests
  - pip install feedparser
  - pip install docker pytest

script:
  - curl 127.0.0.1:5000