language: python
python:
  - 3.8

services:
  - docker

install:
  - docker build -f Dockerfile -t rahulh25/devopsfinalshorturlapi .
  - docker run -d -p 5050:5000 rahulh25/devopsfinalshorturlapi

before_script:
  - pip install -r requirements.txt
  - pip install mock
  - pip install requests
  - pip install feedparser

script:
  - docker ps | grep -q blog